### 测试登录
POST http://localhost:8081/oauth/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 测试登录用户
GET http://localhost:8081/current/user/details
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInRlbmFudElkIjoiMTU0MTIzMDExMzk1MjIzOTYxMCIsInVzZXJUeXBlIjoiNCIsImF2YXRhciI6Imh0dHBzOi8vaXRkYWNoZW4uY29tL3VwbG9hZC8yMDIyLzMvMjAyMjAzMjMyMTMyMDU3MDQxMjIzOTIyNDY4OTQ1OTIucG5nIiwidXNlcklkIjoiMTU0MTIzMDExMzk1MjIzOTYxNyIsImFjY291bnQiOiJhZG1pbiIsImp0aSI6ImNlNTg1ODIwLTU1NjUtNGNmMC05MDY5LTBkNTcwYjkxNjcxYyIsImlzcyI6ImNvbS5naXRodWIuaXRkYWNoZW4iLCJpYXQiOjE2ODI4MzA2MDMsImV4cCI6MTY4Mjg0ODYwM30.hqvf-T8afN1juSUsjDI_0_bhF9bsZHvh16LFprpLLTJVcLZeA2ngmEuhpFf5GJPclhNgriaRwCVV8y9Erem6bQ
