### 测试登录
POST http://localhost:8081/api/oauth/token
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}


### 测试登录用户
GET http://localhost:8081/api/current/user/details
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiI1YWQ2MzQ1OGZjMGQ0NTBlYTMyZWU1ZmI2ZGU5NDk3YyIsImlzcyI6ImNvbS5naXRodWIuaXRkYWNoZW4iLCJleHAiOjE2OTAwMjc2MzgsInN1YiI6ImFkbWluIiwidXNlcklkIjoiMTU0MTIzMDExMzk1MjIzOTYxNyIsIm5pY2tOYW1lIjoi546L5aSn5a64IiwiYWNjb3VudCI6ImFkbWluIiwiZXhwaXJlX2luIjoxNjkwMDI3NjM4MjkyLCJ0ZW5hbnRJZCI6IjE1NDEyMzAxMTM5NTIyMzk2MTAiLCJhdmF0YXIiOiJodHRwczovL2l0ZGFjaGVuLmNvbS91cGxvYWQvMjAyMi8zLzIwMjIwMzIzMjEzMjA1NzA0MTIyMzkyMjQ2ODk0NTkyLnBuZyIsInVzZXJUeXBlIjoiNCJ9.InZRIg_FTQFXKuSaNJCeP_u2sngYIR1Vj95pNCXte4KrLYesAZKJruhczsBnh0t27O7Qzye6TO4YanUzBvPHVGnzJcglmnhdtKjSFiKY7E6PomsErims1a5zJYS-wIuR7UHFgxvNshVUJC8f3ceh_B-ElM2YpI8HJc_-MoN1yHQ


### 获取菜单
GET http://localhost:8081/api/next/menu/routes
Accept: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJuaWNrTmFtZSI6IueOi-Wkp-WuuCIsInRlbmFudElkIjoiMTU0MTIzMDExMzk1MjIzOTYxMCIsInVzZXJUeXBlIjoiNCIsImF2YXRhciI6Imh0dHBzOi8vaXRkYWNoZW4uY29tL3VwbG9hZC8yMDIyLzMvMjAyMjAzMjMyMTMyMDU3MDQxMjIzOTIyNDY4OTQ1OTIucG5nIiwidXNlcklkIjoiMTU0MTIzMDExMzk1MjIzOTYxNyIsImFjY291bnQiOiJhZG1pbiIsImp0aSI6ImY3MzkzMjBjLTA5NDYtNDBlMS1iZjZjLTQyNjRmNzJiMjE1NiIsImlzcyI6ImNvbS5naXRodWIuaXRkYWNoZW4iLCJpYXQiOjE2ODM1NTQxMDMsImV4cCI6MTY4MzU3MjEwM30.zUKbwlu4TL-QefGKogw5hVdhWmTCEAJi_n_W_YwjDZn3HUx_gj2MF082458Stu66PBKmdTy3x8X5k79wtqY38g
