# 端口配置
server:
  port: 8085
  servlet:
    context-path: /fly
    session:
      #会话过期时间默认是30m过期,最少为1分钟, 单位: 秒
      timeout: 18000
#  tomcat:
#    max-connections: 10000 # 最大连接数
#    threads:
#      max: 800 # 最大工作线程数
#      min-spare: 100 # 最小空闲线程数
#      accept-count: 100 # 等待队列长度
#      connection-timeout: 20000

# 日志配置
logging:
  #  config: classpath:fly.xml
  level:
    cn.jay.repository: trace
    ch.qos.logback: error
  #    org.springframework: warn
  file:
    path: ./logs # 配置日志打印目录,默认名称为:spring.log
    name: fly_next.log # 配置日志打印目录和名称,和上面的path选一即可
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

fly:
  app:
    app-id: 4F17C3ED134AD4DA5C830DE9F3D7C02D
    app-name: FLY-NEXT-ADMIN
    ask-uri: http://127.0.0.1:${server.port}${server.servlet.context-path}
  # 数据库加密配置
  datasource:
    encoder: NOOP
  # 文件上传
  oss:
    ## 文件上传类型: LOCAL-本地服务存储; ALI-阿里云存储服务器, 默认是 LOCAL
    type: LOCAL
    local:
      localHttp: http://127.0.0.1:${server.port}${server.servlet.context-path}
      diskFolder: D:/upload/fly-next-admin/
    ali:
      endpoint: oss-cn-chengdu.aliyuncs.com
      access-key-id: 123
      access-key-secret: 123
      bucket: fly

  # 安全认证配置
  security:
    signInPage: /login # 登录页面地址
    signOutUrl: /login # 退出登录成功之后跳转地址
    successForwardUrl: /index # 登录成功后跳转地址
    session:
      sessionInvalidUrl: /login # 登录失效后跳转地址
    matchers: # 不需要登录认证拦截地址
      - /open/**

spring:
  application:
    name: next-admin
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=600s

  # Jackson时区序列化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

  servlet:
    # 限制文件上传大小

    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      # file-size-threshold: 2KB
      file-size-threshold: 10MB
      location: /home/temp
      resolve-lazily: false


  mvc:
    pathmatch:
      # 使用Ant风格的路径匹配器
      matching-strategy: ant_path_matcher


#  task:
#    execution:
#      pool:
#        core-size: 8
#        max-size: 16
#        queue-capacity: 100
#        keep-alive: 60s
#        thread-name-prefix: async-task-
#    scheduling:
#      pool:
#        size: 4
#      thread-name-prefix: sched

  # 静态资源缓存配置
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 365d
          cache-public: true
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
        cache: true
      static-locations: classpath:/static/

  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/fly_next_admin?useUnicode=true&characterEncoding=UTF8&createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: root
    hikari:
      #连接池最大连接数，默认是10
      maximum-pool-size: 50
      #最小空闲连接数量
      minimum-idle: 10
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 600000
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 注意: 默认情况下这个检测是关闭的，如果代码中存在连接泄漏问题，根本发现不了。
      leak-detection-threshold: 60000
      #连接测试查询
      connection-test-query: SELECT 1 FROM DUAL
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      validation-timeout: 5000
      #连接池母子
      pool-name: flyHikariCP


  thymeleaf:
    mode: HTML5
    cache: false
    encoding: utf-8

  session:
    timeout: 18000
    redis:
      namespace: fly:next

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 1800s # 使用时间格式化
      lettuce:
        pool:
          max-active: 20  # 最大连接数
          max-wait: -1    # 最大阻塞等待时间(负数表示没限制)
          max-idle: 5     # 最大空闲
          min-idle: 0     # 最小空闲

# 线程池配置
#  task:
#    execution:
#      pool:
#        core-size: 8
#        max-size: 16
#        queue-capacity: 100
#        keep-alive: 60s
#      thread-name-prefix: async-task-
#    scheduling:
#      pool:
#        size:4
#      thread-name-prefix: scheduling-



# mybatis
mybatis:
  type-aliases-package: com.github.itdachen.**.vo
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页工具
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql