# 日志配置
logging:
  config: classpath:fly.xml
  level:
    cn.jay.repository: trace

fly:
  jwt:
    type: HMAC # token生成方式
    issuer: com.github.itdachen # 签发者
    expires: 18000 # 过期时间, 300分钟
  # 文件上传
  oss:
    ## 文件上传类型: LOCAL-本地服务存储; ALI-阿里云存储服务器, 默认是 LOCAL
    type: LOCAL
    local:
      localHttp: http://127.0.0.1:8080
      diskFolder: D:/upload/
    ali:
      endpoint: oss-cn-chengdu.aliyuncs.com
      access-key-id: 123
      access-key-secret: 123
      bucket: itdachen


spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/fly-next?useUnicode=true&characterEncoding=UTF8&createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: root
    hikari:
      #连接池最大连接数，默认是10
      maximum-pool-size: 8
      #最小空闲连接数量
      minimum-idle: 4
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 30000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      #连接测试查询
      connection-test-query: select 1 from dual
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 45000
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      validation-timeout: 5000
      leak-detection-threshold: 0
      pool-name: adminHikariPC

  data:
    redis:
      database: 3
      host: 127.0.0.1


# mybatis
mybatis:
  type-aliases-package: com.github.itdachen.**.vo
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页工具
pagehelper:
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

