# 端口配置
server:
  port: 8080
  servlet:
   # context-path: /${spring.application.name}
    session:
      #会话过期时间默认是30m过期,最少为1分钟, 单位: 秒
      timeout: 18000

spring:
  application:
    name: next-admin
  profiles:
    active: dev

# 客户端配置
client:
  id: web_app
  # 客户端名称
  name: 基础脚手架
  # 年份
  copyrightYear: 2023

# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS