# 端口配置
#server:
#  port: 8080
#  servlet:
#    session:
#      timeout: 18000


config:
  datasource:
    encoder: AES

# 日志配置
logging:
  config: classpath:fly-admin.xml
  level:
    cn.jay.repository: trace

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: AES{tbJpNVSezRHqKJs274F4f2YNhK3y7Gr+04oHpodd9Wr2fx+MKjYhwefAgELV9q72gSMnWWt5y93+xbZS7+pCBd7e5Fyssw+c1Re6KYZStYzyZ1CF41lxVkL/lIBGzjpJpNV0mYE5etMYc+poFeN4Yn2eXChDdeJ1kIoEGgUf6YYYyf4LrLSkfnynFgS+DKFdTz5Kuy6r5BYA02rcxcrQdkbCzePSBm8H7Ge2DQ1GSRULPSTyrJplNkzk5pM/IiI/xh/D8i2F5DPsrR5pP5kco1llsOMqgMeCvK6oszY4xlvdrR77uTCLHPlOvLirNwRrNzrqNj3oAbn5tRYu6zkx5w==}
    username: AES{YC07e1gh2Ox6HAcP/zPs9w==}
    password: AES{YC07e1gh2Ox6HAcP/zPs9w==}
    hikari:
      #连接池最大连接数，默认是10
      maximum-pool-size: 8
      #最小空闲连接数量
      minimum-idle: 4
      #空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 30000
      #数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      #连接测试查询
      connection-test-query: select 1 from dual
      #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 45000
      #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      validation-timeout: 5000
      leak-detection-threshold: 0
      #连接池母子
      pool-name: adminHikariPC


  thymeleaf:
    mode: HTML5
    cache: false
    encoding: utf-8

  # 安全认证配置
  security:
    browser:
      signInPage: /login
      signOutUrl: /login
      successForwardUrl: /index
      session:
        sessionInvalidUrl: /login

  redis:
    host: 127.0.0.1
    database: 3


# mybatis
mybatis:
  type-aliases-package: com.github.itdachen.**.vo
  mapperLocations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 分页工具
pagehelper:
  helperDialect: mysql
  # 超过总页数是否返回最后一页数据
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

oss:
  local:
    uploadPath: D:/upload/